### ISSUE TITLE
NewBie - Need help to create store

### ISSUE THREAD

**Issue by kieusonlam** [Xerios/mobx-isomorphic-starter#1]
Hi,

I'm pretty new to React, and MobX. I found this starter-project, every so clear and i really like it.

I trying to create some small thing to learn like a Timer.

I created 2 file

**/src/client/containers/pages/Timer/store.js**

```
import { observable, action, autorun } from 'mobx';

class TimerStore {
  @observable counter = 0;
}

const store = new TimerStore;

export default store;
```

**/src/client/containers/pages/Timer/Timer.js**

```
import React from 'react'
import { inject, observer } from 'mobx-react'

@observer(["state","store"])
export default class Timer extends React.Component {
    static fetchData({state, store}){
        state.app.title = 'Timer'
    }
    render() {
        return <section>
            <h1>Timer</h1>
            <p>{this.props.store.timerStore.counter}</p>
        </section>
    }
}
```

**/src/client/routes.js**
Add a new route

`<Route path="timer"  getComponent={requireAsync('Timer/Timer')}/>`

Import store to client
**/src/client/index.js**

```
...

import { store as timerStore } from './containers/pages/Timer/store'

// Import our styles
require('./assets/css/index.scss')

// Initialize stores & inject server-side state into front-end
const state = createState(window.__STATE)
const store = {timerStore}

...
```

I got this error from Browser
`400: An error has occured : TypeError: Cannot read property 'counter' of undefined`

And this error from console
`[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These functions should never throw exceptions as MobX will not always be able to recover from them. Please fix the error reported after this message or enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'Timer#0.render()'. For more details see https://github.com/mobxjs/mobx/issues/462`

What did i do wrong and how to make it right. Thanks!

**Comment by Xerios** [comment]
Did you set the store object in the render.js as well?

**Comment by kieusonlam** [comment]
Yes i did same thing i did in index.js file in client folder

```
...

import { store as timerStore } from '../client/containers/pages/Timer/store'

// Handles page rendering ( for isomorphic / server-side-rendering too )
//----------------------
export default (req, res) => {

    // Create state to transfer
    const state = createState()

    // Set host variable to header's host
    state.app.host = req.headers.host

    // Create store object to transfer
    const store = {timerStore}
...
```

**Comment by Xerios** [comment]
You're exporting store as default, which is nameless, this allows you to name your variable however you want when importing. So all you need to do is change your store imports to:
`import timerStore from '../client/containers/pages/Timer/store'`

**or** you could also export store as a non default member, then something like this : 
`export const store = new TimerStore` should do.

Hopefully that fixes your problems :)

**Comment by kieusonlam** [comment]
Thanks @Xerios ! That solved it for me.
