### ISSUE TITLE
Why state and store

### ISSUE THREAD

**Issue by xrado** [Xerios/mobx-isomorphic-starter#2]
what is the difference?

**Comment by Xerios** [comment]
You can imagine state being a database for key and values, while store is what contains all re-usable methods and actions. ( e.g. store.auth.LogIn() which checks for logged in state and does something with it )

At least that's how I portray it.

**Comment by xrado** [comment]
yes, but mobx store or observable object can be both, thats why I'm wandering whats the point of state, sure you can have multiple stores (one called state). I thought there is special reason

**Comment by Xerios** [comment]
Good point and I agree. I just based myself on how redux organizes their stuff, no particular reason at all :)

If you think this starter can still look good without the store, I'd love to hear more about your point of view.

**Comment by Xerios** [comment]
After reflecting on my structural choices I decided to remove Store.
