### ISSUE TITLE
How to support mobx @actions

### ISSUE THREAD

**Issue by anthony-dandrea** [Xerios/mobx-isomorphic-starter#3]
Is there a way to handle mobx actions with this setup? Right now when I see my store I can only spot my observables. When I try access my actions on the store they are undefined.

PS Awesome project. This starter has been a huge help for getting my app bootstrapped. Thank you.

**Comment by Xerios** [comment]
Thanks, glad you find it useful.

With one of the recent commits I made, I removed the store object.
Normally you should be able to place functions/actions in the state, but I'll look into it and add a simple example to make it clearer :)

You can also reimplement the separate store object yourself if you look at my latest commits, it's basically done the same way I inject state into components. ( Files to edit would be : render client and server side + fetchdata function if you need it in the static fetchdata functions )

**Comment by Xerios** [comment]
I've pushed out few updates with a working example.
The commits should be separated clearly enough to see how I did it, hope it helps !

**Comment by anthony-dandrea** [comment]
Thank you, I really appreciate it 😃
