### ISSUE TITLE
little confused with @action

### ISSUE THREAD

**Issue by L-x-C** [Xerios/mobx-isomorphic-starter#5]
in Browse.jsx
if i remove @action,just
`static fetchData({state, actions, query})`

it still works well
So what's the necessary with using @action?

Thanks a lot

**Comment by Xerios** [comment]
As far as I understood, action groups all the observable changes that happens inside the function. This way the changes are only fired after the function finishes executing. Of course it's optional, but for performance's sake it's handy :)
