### ISSUE TITLE
How to fetchData in sequence while the first one is asynchronously

### ISSUE THREAD

**Issue by L-x-C** [Xerios/mobx-isomorphic-starter#7]
If there is a fetchData in App.jsx, and there is another fetchData in About.jsx

In App.jsx
```
@action static fetchData({state}){
  setTimeout(() => {
    console.log('a')
  }, 1000)
}
````

In About.jsx
```
@action static fetchData({state}){
    console.log('b')
    state.app.title = 'About'
}
```

In this situation, it will console 'b' first, and 'a' next.
But I want to console 'a' first, and 'b' next.

Really hope to get your help，thx~

**Comment by Xerios** [comment]
Have you tried returning a promise? Otherwise the setTimeout will always be last due to it being a timeout and all..  

Try something like this, for both of those fetchData functions.
```
return new Promise((resolve)=> setTimeout(() => {
                console.log('a')
                resolve()
}, 1000))
```

I'm not at home atm, so for now this is all I can suggest :)

**Comment by L-x-C** [comment]
Not work...

```
    this.state.components.filter(c => c.fetchData).forEach(c => {
        c.fetchData({ state, params, actions, query })
    })
```
I'm thinking maybe not using forEach here, but async.eachSeries instead, I'll try, thx anyway

**Comment by L-x-C** [comment]
```
async.eachSeries(this.state.components.filter(c => c. fetchData), (c, callback) => {
  let fetchFn = c. fetchData({ state, params, actions, query });
  if (fetchFn) {
    fetchFn.then(res => {
      callback()
    })
  } else {
    callback()
  }
});
```

it seems to work
